Show errors
gautamkrishnar/keepalive-workflow pull request #8
Opened 2022-12-04 15:05 UTC by iTrooz

Right now when the try/catch catch a dictionary, it will apply .toString() to it, printing `Error: [object Object]` to the console
This PR aims to fix that

(If you are interested, in my case the error was that git is not installed on a Ubuntu 16.04 docker image)

2022-12-04 16:06 UTC, iTrooz commented
Draft because I realized the logging is not complete, the action still fails for me and it still doesn't log anything

2022-12-04 16:42 UTC, iTrooz commented
Good !

2022-12-04 21:55 UTC, gautamkrishnar requested changes
@iTrooz Can you please revert the changes made to dist/index.js

2022-12-04 22:15 UTC, iTrooz commented
Sure !

2022-12-05 13:54 UTC, merged

2022-12-05 13:54 UTC, gautamkrishnar commented
@iTrooz merged after making some changes, thanks for the contribution

2022-12-05 14:05 UTC, gautamkrishnar commented
@all-contributors please add @iTrooz for code